name: "Automerge Dependabot PRs"

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]

jobs:
  automerge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto-merge Dependabot PRs when checks pass
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge using pascalgn/automerge-action
        uses: pascalgn/automerge-action@v0.16.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          # require the label 'automerge' to be present on the PR
          required_labels: automerge
          # restrict to Dependabot authored PRs
          allowed_authors: dependabot[bot]
          # wait for status checks to be green
          merge_when_all_checks_pass: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
